# SITE CONFIGURATION
title: Hey, I'm Jason. # your site title
author: Jason Hyland # You :P
description: > # Meta description of Homepage
  I'm a developer and general bit twiddler based in the UK. You've landed on my projects page - thanks for visiting! This is a place where I store some really random home projects I've worked on.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://projects.jasonhyland.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Jason Hyland
  links:
    - https://linkedin.com/JasonHyland

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}


tagline: >
  I'm a developer and general bit twiddler based in the UK. You've landed on my projects page - thanks for visiting! This is a place where I store some really random home projects I've worked on. I hope you like them!

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jason.hyland@gmail.com # email for form submission

github_username:  jasonhyland # replace with your_github_username or comment to remove link from footer

disqus:
  shortname: jasonhyland # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/
 
compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag